---
application:
  name: "peerjs-server"
  project: "peerjsserver"
  organization: "QoveryCommunity"
routers:
- name: "main-peerjs-server"
  routes:
  - application_name: "peerjs-server"
    paths:
    - "/*"
